id: I7AAE026A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T06:24:22+00:00'
last_modified: '2022-06-10T09:12:26.839261+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC327
  title: ཕྱག་རྒྱ་ཆེན་པོའི་སྒྲོས་འབུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    21EB:
      image_group_id: I4PD4421
      title: Volume 1 of phyag rgya chen po'i sgros 'bum/
      total_pages: 286
      order: 1
      base_file: 21EB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
